#!/usr/bin/env node

const run = require('./lib/utils/run');
const path = require('path');
const { writeFile } = require('then-fs');

async function main() {
  const package = require('./package');
  const [major, minor, patch] = package.version.split(/\./g).map(n => +n);
  package.version = `${major}.${minor}.${patch + 1}`;
  await writeFile(path.join(__dirname, 'package.json'), JSON.stringify(package, null, 2));
  const commands = [
    `git add *`,
    `git commit -am "🚀"`,
    `git push origin master`,
  ];
  for(let command of commands) await run(command);
}

main().catch(error => console.log(error));
